version: '3.4'

services:

  # The Java bot process -- uses dev.Dockerfile in ./docker/
  # Will attempt to restart 3 times.
  bot:
    image: ib.ai
    restart: on-failure:3
    build:
      context: ./
      dockerfile: dev.Dockerfile
    env_file:
      - bot.env
    depends_on:
      - db

  # Redis database
  # Running on port 6379, on a failure it will restart itself
  # Connect via the URL 'redis://db:6379'
  db:
    restart: always
    image: redis
    volumes:
      - db-data:/data

volumes:
  # Database persistence
  db-data: